---
apiVersion: v1
kind: BuildConfig
metadata:
  name: "ConfigureJenkinsPipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/RHsyseng/openshift-pipeline-library"
      ref: "master"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
        jenkinsfilePath: jenkins/jobs/configureJenkinsOpenShift.groovy
