---
# ----------------------------
# Running
# ----------------------------
# TODO: This should be modified to include secrets
# The jenkins modules execute using the API so the play can just execute locally.
# ansible-playbook -i localhost, -c local installseedjob.yml
# ----------------------------
- name: Install Container Zone Seed Jobs
  hosts: localhost
  gather_facts: False
  vars:
    start_build: |
      import jenkins.model.*
      import hudson.model.*
      Jenkins.instance.getAllItems(FreeStyleProject).each {it ->
      def pattern = 'checkImageHealthSeed'
      def m = it.getName() =~ pattern
          if(m) {
              it.scheduleBuild()
          }
      }

    approve_script: |
      import org.jenkinsci.plugins.scriptsecurity.scripts.*
      ScriptApproval sa = ScriptApproval.get();
      for (ScriptApproval.PendingScript pending : sa.getPendingScripts()) {
          sa.approveScript(pending.getHash());
      }

  tasks:
# ----------------------------
# Create Seed Job
# ----------------------------
# This is an example of creating a seed job to build a pipeline job
# that uses the Job DSL plugin.
# ----------------------------
    - name: Create Seed Job for checkHealthGradePipeline (Job DSL)
      jenkins_job:
        config: "{{ lookup('file', 'templates/checkImageHealthSeed.xml') }}"
        name: checkImageHealthSeed
        url: http://10.53.252.84:8080
        user: admin
        token: 66d28ba4dbd8731e1148273158eb4add

# ----------------------------
# Jenkins Start Job
# ----------------------------
# This will start the seed job that we just added
# NOTE: this will most likely fail.
# ----------------------------
    - name: Jenkins Start Job
      jenkins_script:
        script: "{{ start_build }}"
        url: http://10.53.252.84:8080
        user: admin
        password: admin
